version: '3'
services:
  app:
    build: .
    container_name: capstone
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/capstone
      - JWT_SECRET=WRBghAWA0aNFGHR4SCihbV939hjk3S
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - /app/node_modules/
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: capstone
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: